name: build-check
run-name: PR of ${{ github.actor }}
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 2
      - name: ubuntu-setup
        run: |
          sudo apt-get update
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get install clang-format
      - name: format-check
        run: |
          git branch
          git log -n 5 --format="%h %B"
          echo "git-clang-format --diff --commit ${{github.event.pull_resquest.head.sha}}"
          git-clang-format --diff --commit ${{github.event.pull_resquest.head.sha}}
